## 에러 처리의 필요성

발생한 에러에 대해 대처하지 않으면 프로그램은 강제 종료됨

## try … catch … finally 문

에러가 발생하면 에러 처리 코드로 점프하는 방법

```jsx
try {
	// 실행 코드
} catch(err) {
	// try 코드 블록에서 에러 발생 시 점프
} finally {
	// 에러 발생과 상관없이 반드시 실행
}
```

## Error 객체

```jsx
const err = new Error('에러 설명 메시지')
err.message // 에러 설명 메시지
err.stack // 에러 발생시 콜스택의 호출 정보를 나타내는 문자열
```

## throw 문

에러 객체를 생성한다고 에러가 발생하는 것은 아님

```jsx
throw err;
```

## 에러의 전파

에러는 호출자 방향으로 전파됨

비동기 함수인 setTimeout이나 프로미스 후속 처리 메서드의 콜백 함수는 호출자가 없음 → 콜스택의 가장 하부에 존재하게 됨
